version: "2"
run:
  go: 1.23.5
linters:
  default: all
  disable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errname
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gosec
    - govet
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - recvcheck
    - revive
    - spancheck
    - staticcheck
    - tagalign
    - tagliatelle
    - thelper
    - unparam
    - usetesting
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocognit:
      min-complexity: 65
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - validator/web/site_data.go
      - .*_test.go
      - proto
      - tools/analyzers
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - validator/web/site_data.go
      - .*_test.go
      - proto
      - tools/analyzers
      - third_party$
      - builtin$
      - examples$
